[tool.black]
line-length = 120
target-version = ['py310']
exclude = '''
/(
    \.eggs
  | \.git
  | \.idea
  | \.pytest_cache
  | _build
  | build
  | dist
  | venv
)/
'''


[tool.poetry]
name = "FastFlix"
version = "6.2.0a0"
description = "GUI Encoder"
license = "MIT"
authors = ["Chris Griffith <chris@cdgriffith.com>", ]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
appdirs = "~=1.4"
chardet = ">=5.1.0,<5.2.0"
colorama = ">=0.4,<1.0"
coloredlogs = ">=15.0,<16.0"
iso639-lang = "0.0.9"
mistune = ">=2.0,<3.0"
pathvalidate = ">=2.4,<3.0"
psutil = ">=5.9,<6.0"
pydantic = ">=1.9,<2.0"
pyside6 = ">=6.3,<7.0"
python-box = {version = ">=6.0,<7.0", extras = ["all"]}
requests = ">=2.28,<3.0"
reusables = ">=0.9.6,<0.10.0"
